import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const kings = [
  { id: 1, name: '태조', orderNumber: 1, shortDescription: '조선을 세운 왕, 이성계', description: '고려의 장수였을 때 홍건적과 왜구를 물리치는 공을 세웠으며, 위화도 회군으로 권력을 잡은 뒤 조선을 세웠다. 이후 수도를 한양으로 옮겨 나라의 기틀을 닦았다.' },
  { id: 2, name: '정종', orderNumber: 2, shortDescription: '조선의 제2대 왕, 과도기적 군주', description: '태조의 둘째 아들로, 이방원의 정치적 영향 아래 왕위에 올랐다. 실권은 약했으나 혼란한 정국을 넘기는 역할을 했으며, 왕위에 오래 머물지 않고 동생 이방원에게 양위하였다.' },
  { id: 3, name: '태종', orderNumber: 3, shortDescription: '조선의 제3대 왕, 절대왕권 구축자', description: '태조의 다섯째 아들로, 왕권의 난을 일으켜 임금이 된 뒤 왕권 강화에 힘썼다. 반대 세력을 제거하고, 6조 직계제를 시행하는 등 왕 중심 정치에 집중하였다.' },
  { id: 4, name: '세종', orderNumber: 4, shortDescription: '조선의 제4대 왕, 훈민정음 창제자', description: '백성을 위해 훈민정음을 창제했다. 집현전을 통해 인재를 양성하고, 측우기와 자격루 등 과학 기술을 발전시켰으며, 4군 6진을 개척하여 영토를 확장하는 등 조선의 전성기를 이룩했다.' },
  { id: 5, name: '문종', orderNumber: 5, shortDescription: '조선의 제5대 왕, 문무 겸비의 군주', description: '세종을 보좌하며 측우기 제작 등에 기여했고 유학에 뛰어났다. 재위 기간이 짧았으나 고려사 등 역사서를 편찬하고 병법과 군사 제도를 정비하는 등 국방력 강화와 문화 발전에 힘썼다.' },
  { id: 6, name: '단종', orderNumber: 6, shortDescription: '조선의 제6대 왕, 어린 나이의 비극', description: '문종의 아들로 12세의 어린 나이에 왕위에 올랐으나 정권이 불안정했다. 결국 숙부인 수양대군이 일으킨 계유정난으로 인해 왕위를 빼앗기고 영월로 유배되었다가 죽음을 당했다.' },
  { id: 7, name: '세조', orderNumber: 7, shortDescription: '조선의 제7대 왕, 피로 세운 왕권', description: '계유정난을 일으켜 권력을 잡은 후 왕위에 올랐다. 6조 직계제를 부활시켜 왕권을 강화했으며, 관직에 있는 관리에게만 토지를 주는 직전법을 시행했으며, 경국대전 편찬을 시작했다.' },
  { id: 8, name: '예종', orderNumber: 8, shortDescription: '조선의 제8대 왕, 짧고 강렬한 치세', description: '세조의 둘째 아들로 즉위했으나 재위 14개월 만에 짧은 생을 마감했다. 부왕의 뜻을 이어 경국대전 편찬을 지속하였으며, 남이의 모반 사건을 처리하며 왕권 안정에 힘썼다.' },
  { id: 9, name: '성종', orderNumber: 9, shortDescription: '조선의 제9대 왕, 조선 제도의 완성', description: '조선의 근본 법전인 경국대전을 반포하여 통치 체제를 완성했다. 홍문관을 설치하여 학문을 장려하고 경연을 활성화했으며, 사림 세력을 등용하여 훈구 세력을 견제하는 등 균형을 맞췄다.' },
  { id: 10, name: '연산군', orderNumber: 10, shortDescription: '조선의 제10대 왕, 두 번의 사화', description: '조선 최초로 폐위된 왕이다. 어머니 폐비 윤씨 사건 등을 계기로 무오사화와 갑자사화를 일으켜 많은 선비를 숙청했다. 극심한 실정과 폭정을 거듭하다 중종반정으로 왕위에서 쫓겨났다.' },
  { id: 11, name: '중종', orderNumber: 11, shortDescription: '조선의 제11대 왕, 반정 개혁의 늪', description: '반정 후 즉위해 조광조를 등용하고 도학 정치와 현량과를 실시하며 개혁을 시도했다. 그러나 훈구파의 음모로 인해 의심을 품고 기묘사화를 일으켜 조광조와 사림 세력을 숙청했다.' },
  { id: 12, name: '인종', orderNumber: 12, shortDescription: '조선의 제12대 왕, 효성 깊은 군주', description: '중종의 맏아들로 성품이 어질고 효성이 지극했다. 기묘사화로 화를 입은 조광조 등 사림들을 신원하며 개혁을 시도했으나, 재위 8개월 만에 이른 나이로 세상을 떠났다.' },
  { id: 13, name: '명종', orderNumber: 13, shortDescription: '조선의 제13대 왕, 외척 발흥 시대', description: '어린 나이에 즉위하여 문정왕후가 수렴청정을 했다. 외척 간의 권력 다툼으로 을사사화가 발생해 사림이 큰 화를 입었고, 임꺽정의 난과 을묘왜변이 일어나는 등 대내외로 혼란했다.' },
  { id: 14, name: '선조', orderNumber: 14, shortDescription: '조선의 제14대 왕, 왜란을 겪다', description: '사림 세력을 대거 등용해 정치를 주도했다. 재위 기간 중 임진왜란이라는 큰 국난을 맞이했으나, 이순신 장군과 의병들의 활약에 힘입어 전란을 극복하고 나라를 지켜냈다.' },
  { id: 15, name: '광해군', orderNumber: 15, shortDescription: '조선의 제15대 왕, 대동법의 선구자', description: '전후 복구에 힘쓰며 공납의 폐단을 줄이기 위해 대동법을 처음 실시했다. 명과 후금 사이에서 실리적인 중립외교를 펼쳐 전쟁을 막았으나, 인조반정으로 결국 폐위되었다.' },
  { id: 16, name: '인조', orderNumber: 16, shortDescription: '조선의 제16대 왕, 반정의 주인공', description: '서인 세력과 함께 인조반정을 일으켜 광해군을 몰아내고 즉위했다. 친명배금 정책을 고수하다 정묘호란과 병자호란을 초래했고, 삼전도에서 청에 항복하는 굴욕을 겪었다.' },
  { id: 17, name: '효종', orderNumber: 17, shortDescription: '조선의 제17대 왕, 북벌론의 기수', description: '국력을 키우고 나라의 자존심을 세우기 위해 군제 개혁과 군사력 강화에 매진했다. 대동법을 충청도와 전라도까지 확대 실시하여 백성의 삶을 안정시키는 데도 큰 공을 세웠다.' },
  { id: 18, name: '현종', orderNumber: 18, shortDescription: '조선의 제18대 왕, 붕당정치기 국왕', description: '왕실의 의례 문제를 두고 서인과 남인이 대립한 예송논쟁 시기의 왕이다. 치열한 붕당정치 속에서도 중심을 잡고 왕권을 지켰으며, 훈련별감을 재건해 국방 체제를 다졌다.' },
  { id: 19, name: '숙종', orderNumber: 19, shortDescription: '조선의 제19대 왕, 절대왕권의 군주', description: '환국정치를 통해 신권을 누르고 강력한 절대왕권을 확립했다. 대동법을 전국에 확대하고 화폐인 상평통보를 널리 유통시켜 조선 후기 상품 화폐 경제 발전에 크게 기여했다.' },
  { id: 20, name: '경종', orderNumber: 20, shortDescription: '조선의 제20대 왕, 비운의 단명 군주', description: '치열한 당쟁 속에서 왕위에 올랐다. 신하들의 대립이 극에 달한 시기였으나, 백성들의 세금 부담을 줄이기 위해 호포제 시행을 논의하는 등 민생 안정을 도모했다.' },
  { id: 21, name: '영조', orderNumber: 21, shortDescription: '조선의 제21대 왕, 탕평책의 선구자', description: '붕당정치의 폐단을 막기 위해 능력 중심의 탕평책을 본격적으로 실시했다. 서원을 정리하고 균역법을 제정해 백성들의 군포 부담을 덜어주었으며, 조선 역사상 가장 오랜 기간 재위했다.' },
  { id: 22, name: '정조', orderNumber: 22, shortDescription: '조선의 제22대 왕, 조선의 개혁 군주', description: '규장각을 육성해 인재를 키우고 신진 세력을 등용하며 개혁 정치를 이끌었다. 수원 화성을 축조하여 상업과 국방의 중심지로 삼았고, 국왕 친위 부대인 장용영을 설치해 왕권을 강화했다.' },
  { id: 23, name: '순조', orderNumber: 23, shortDescription: '조선의 제23대 왕, 비운의 침체기 군주', description: '어린 나이에 즉위하여 안동 김씨 등 외척 세력이 주도하는 세도정치 시기를 맞이했다. 국정 통제력이 약화되는 침체기 속에서도 공노비를 해방하는 등 사회적 모순을 해결하려 노력했다.' },
  { id: 24, name: '헌종', orderNumber: 24, shortDescription: '조선의 제24대 왕, 최연소 즉위', description: '역대 국왕 중 가장 어린 나이인 8세에 즉위했다. 비록 외척의 세도정치가 지속되어 정치는 불안정했으나, 부녀자를 보호하고 향촌 사회를 안정시키기 위한 민생 법령을 다수 정비했다.' },
  { id: 25, name: '철종', orderNumber: 25, shortDescription: '조선의 제25대 왕, 방계 혈통의 국왕', description: '강화도에서 평민처럼 살다가 영조의 혈통을 이어받아 왕위에 올랐다. 세도정치의 폐단으로 삼정의 문란이 극에 달하자, 이를 바로잡기 위해 삼정이정청을 설치하는 등 개혁을 시도했다.' },
  { id: 26, name: '고종', orderNumber: 26, shortDescription: '조선의 제26대 왕, 대한제국 선포', description: '급변하는 국제 정세 속에서 근대 국가로의 발전을 꾀했다. 국호를 대한제국으로 바꾸고 스스로 황제의 자리에 올랐으며, 광무개혁을 추진해 군사와 경제 등 다방면의 근대화를 이끌었다.' },
  { id: 27, name: '순종', orderNumber: 27, shortDescription: '조선의 제27대 왕, 마지막 황제', description: '대한제국의 두 번째 황제이자 조선 왕조의 마지막 군주이다. 일제의 강압과 국권 침탈이라는 역사적 비극 속에서도 황실의 자존심을 지키려 했으며, 그의 장례식은 6·10 만세운동의 계기가 되었다.' },
];

const kingTags = [
  { kingId: 1, tags: ['#조선시대', '#왕', '#고려장수', '#건국', '#한양', '#개혁정치'] },
  { kingId: 2, tags: ['#조선시대', '#왕', '#허수아비', '#개경환도', '#안분지족', '#유유자적'] },
  { kingId: 3, tags: ['#조선시대', '#왕', '#왕자의난', '#왕권강화', '#신문고', '#냉혹한'] },
  { kingId: 4, tags: ['#조선시대', '#왕', '#훈민정음', '#해동성군', '#과학발전', '#영토확장'] },
  { kingId: 5, tags: ['#조선시대', '#왕', '#문무겸비', '#측우기제작', '#고려사', '#국방강화'] },
  { kingId: 6, tags: ['#조선시대', '#왕', '#어린임금', '#계유정난', '#영월유배'] },
  { kingId: 7, tags: ['#조선시대', '#왕', '#피의군주', '#왕권강화', '#6조직계제', '#직전법'] },
  { kingId: 8, tags: ['#조선시대', '#왕', '#짧은재위', '#둔전경작', '#남이의난'] },
  { kingId: 9, tags: ['#조선시대', '#왕', '#문물완성', '#경국대전반포', '#홍문관설치', '#동국통감'] },
  { kingId: 10, tags: ['#조선시대', '#왕', '#폐위', '#무오사화', '#갑자사화', '#중종반정'] },
  { kingId: 11, tags: ['#조선시대', '#왕', '#반정공신', '#조광조', '#기묘사화', '#비변사설치'] },
  { kingId: 12, tags: ['#조선시대', '#왕', '#효심', '#단명', '#현량과부활', '#사림신원'] },
  { kingId: 13, tags: ['#조선시대', '#왕', '#수렴청정', '#을사사화', '#인재발탁'] },
  { kingId: 14, tags: ['#조선시대', '#왕', '#임진왜란', '#국난극복', '#방계출신', '#사림등용'] },
  { kingId: 15, tags: ['#조선시대', '#왕', '#전후복구', '#대동법', '#중립외교', '#비운의폐위'] },
  { kingId: 16, tags: ['#조선시대', '#왕', '#인조반정', '#호란', '#삼전도', '#영정법'] },
  { kingId: 17, tags: ['#조선시대', '#왕', '#인질신세', '#북벌론', '#군사력강화', '#대동법확대'] },
  { kingId: 18, tags: ['#조선시대', '#왕', '#상복논쟁', '#예송논쟁', '#붕당정치'] },
  { kingId: 19, tags: ['#조선시대', '#왕', '#환국정치', '#절대왕권', '#상평통보'] },
  { kingId: 20, tags: ['#조선시대', '#왕', '#당쟁의희생양', '#단명', '#민생안정노력'] },
  { kingId: 21, tags: ['#조선시대', '#왕', '#탕평책', '#균역법', '#최장수재위'] },
  { kingId: 22, tags: ['#조선시대', '#왕', '#개혁군주', '#규장각', '#수원화성', '#장용영'] },
  { kingId: 23, tags: ['#조선시대', '#왕', '#세도정치서막', '#공노비해방', '#홍경래의난'] },
  { kingId: 24, tags: ['#조선시대', '#왕', '#최연소즉위', '#8세왕', '#외척정치'] },
  { kingId: 25, tags: ['#조선시대', '#왕', '#강화도령', '#방계혈통', '#삼정의문란', '#삼정이정청'] },
  { kingId: 26, tags: ['#대한제국', '#황제', '#대한제국', '#아관파천', '#황제즉위', '#광무개혁'] },
  { kingId: 27, tags: ['#대한제국', '#황제', '#마지막황제', '#국권침탈', '#망국의아픔'] },
];

const spots = [
  { id: 1,  contentId: '147656',  name: '경기전',               areaCode: 37, sigunguCode: 12, description: '조선 왕조의 발상지인 전주에 세워진 경기전은 태조 이성계의 기상과 수난의 역사를 품은 곳이다. 새 나라를 디자인한 태조의 영정(어진)이 봉안되며 왕조의 신성한 성역이 되었으나, 선조 시기 임진왜란으로 전소되는 비극을 맞았다. 다행히 어진을 극적으로 대피시켜 정통성을 지켜냈고 이후 중건되었다. 위대한 시작과 국난의 시련을 온몸으로 증언하는 현장이다.' },
  { id: 2,  contentId: '250331',  name: '전동성당',              areaCode: 37, sigunguCode: 12, description: null },
  { id: 3,  contentId: '147684',  name: '전주향교',              areaCode: 37, sigunguCode: 12, description: null },
  { id: 4,  contentId: '3056468', name: '서학동 예술마을',       areaCode: 37, sigunguCode: 12, description: null },
  { id: 5,  contentId: '126621',  name: '오목대',                areaCode: 37, sigunguCode: 12, description: null },
  { id: 6,  contentId: '126622',  name: '풍남문',                areaCode: 37, sigunguCode: 12, description: null },
  { id: 7,  contentId: '3352874', name: '국립무형유산원',        areaCode: 37, sigunguCode: 12, description: null },
  { id: 8,  contentId: '3497454', name: '의정부지 역사유적광장', areaCode: 1,  sigunguCode: 23, description: '정종 2년 도평의사사를 폐지하고 조선 최고 행정기관인 의정부를 설치한 역사적 장소이다. 광화문광장 동편에 위치하며, 오랜 발굴조사를 거쳐 최근 \'의정부지 역사유적광장\'으로 새롭게 단장되어 시민들에게 공개되었다. 이곳에서 정종이 단행했던 관제 개혁과 조선 행정의 기틀을 직접 느껴볼 수 있다.' },
  { id: 9,  contentId: '1849416', name: '대한민국역사박물관',    areaCode: 1,  sigunguCode: 23, description: null },
  { id: 10, contentId: '126508',  name: '경복궁',                areaCode: 1,  sigunguCode: 23, description: '사림을 등용해 유교 정치를 펼치려던 선조의 치세는 임진왜란이라는 큰 국난으로 얼룩졌다. 당시 경복궁 전체가 불타면서 연회가 열리던 아름다운 경회루도 돌기둥만 남긴 채 전소되었다. 국난의 시련과 조선 전기 왕조의 비극적인 끝을 상징적으로 보여주는 가슴 아픈 역사의 현장이다.' },
  { id: 11, contentId: '3056152', name: '열린송현녹지광장',      areaCode: 1,  sigunguCode: 23, description: null },
  { id: 12, contentId: '250358',  name: '우정총국',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 13, contentId: '2992891', name: '사직단',                areaCode: 1,  sigunguCode: 23, description: null },
  { id: 14, contentId: '129259',  name: '태종대',                areaCode: 32, sigunguCode: 18, description: '강원도 횡성의 태종대는 조선 태종 이방원이 은거하던 스승 원천석을 관직에 등용하고자 직접 찾아왔던 역사적 장소이다. 태종이 스승을 기다리며 머물렀던 바위라는 뜻에서 \'주필대\' 혹은 \'태종대\'라 불리게 되었으며, 현재는 비석과 비각이 세워져 있다. 왕의 간절함과 끝내 고려에 절개를 지킨 스승의 일화가 수려한 계곡과 어우러진 의미 깊은 곳이다.' },
  { id: 15, contentId: '125587',  name: '치악산국립공원',        areaCode: 32, sigunguCode: 9,  description: null },
  { id: 16, contentId: '2951595', name: '안흥찐빵모락모락마을',  areaCode: 32, sigunguCode: 18, description: null },
  { id: 17, contentId: '3489648', name: '횡성호수길',            areaCode: 32, sigunguCode: 18, description: null },
  { id: 18, contentId: '125807',  name: '풍수원성당',            areaCode: 32, sigunguCode: 18, description: null },
  { id: 19, contentId: '125761',  name: '구룡사',                areaCode: 32, sigunguCode: 9,  description: null },
  { id: 20, contentId: '128748',  name: '운암정',                areaCode: 32, sigunguCode: 18, description: null },
  { id: 21, contentId: '129792',  name: '세종대왕 기념관',       areaCode: 1,  sigunguCode: 11, description: '세종대왕의 성덕과 위업을 기리고 한글 정신을 계승하기 위해 설립된 문화 공간이다. 기념관 내부에는 세종대왕의 생애와 업적을 담은 유물, 의복, 훈민정음 관련 자료가 체계적으로 전시되어 있다. 야외정원에는 신도비와 영릉 석물 등 보물급 유적들이 함께 보존되어 있어 세종의 찬란한 역사적 발자취를 한눈에 살펴볼 수 있는 상징적인 장소이다.' },
  { id: 22, contentId: '126500',  name: '홍릉시험림',            areaCode: 1,  sigunguCode: 11, description: null },
  { id: 23, contentId: '126527',  name: '영휘원과 숭인원',       areaCode: 1,  sigunguCode: 11, description: null },
  { id: 24, contentId: '337508',  name: '연화사',                areaCode: 1,  sigunguCode: 11, description: null },
  { id: 25, contentId: '3057945', name: '김희수아트센터',        areaCode: 1,  sigunguCode: 11, description: null },
  { id: 26, contentId: '231977',  name: '서울약령시한의약박물관', areaCode: 1,  sigunguCode: 11, description: null },
  { id: 27, contentId: '129833',  name: '경희대학교 중앙박물관', areaCode: 1,  sigunguCode: 11, description: null },
  { id: 28, contentId: '125545',  name: '동구릉 현릉 문종왕릉', areaCode: 31, sigunguCode: 6,  description: '경기 구리에 위치한 동구릉 내 현릉은 조선 제5대 국왕 문종과 현덕왕후 권씨가 묻힌 왕릉이다. 하나의 정자각을 두고 서로 다른 언덕에 능이 조성된 동원이강릉 형태를 띠고 있다. 세자 시절 측우기 발명에 기여하는 등 영특했으나 재위 2년여 만에 짧은 생을 마감한 문종의 발자취를 울창한 소나무 숲길을 걸으며 기릴 수 있는 고즈넉한 장소다.' },
  { id: 29, contentId: '4075415', name: '고구려대장간마을',      areaCode: 31, sigunguCode: 6,  description: null },
  { id: 30, contentId: '129550',  name: '장자호수공원',          areaCode: 31, sigunguCode: 6,  description: null },
  { id: 31, contentId: '129554',  name: '구리타워',              areaCode: 31, sigunguCode: 6,  description: null },
  { id: 32, contentId: '228874',  name: '구리한강시민공원',      areaCode: 31, sigunguCode: 6,  description: null },
  { id: 33, contentId: '3090931', name: '구리전통시장',          areaCode: 31, sigunguCode: 6,  description: null },
  { id: 34, contentId: '129549',  name: '구리시곤충생태관',      areaCode: 31, sigunguCode: 6,  description: null },
  { id: 35, contentId: '130667',  name: '장릉 단종역사관',       areaCode: 32, sigunguCode: 8,  description: '강원도 영월의 장릉과 단종역사관은 단종의 사후 영면을 기리고 그의 전 생애를 조명하는 상징적인 장소다. 단종역사관에서는 소년 왕의 탄생부터 유배, 승하에 이르는 슬픈 역사와 복위 과정을 유물과 자료로 깊이 있게 살펴볼 수 있다. 역사관을 관람한 후 한양을 벗어난 유일한 왕릉인 장릉의 소나무 숲길을 걸으며 단종의 넋을 고즈넉하게 추모하기 좋다.' },
  { id: 36, contentId: '125785',  name: '청령포',                areaCode: 32, sigunguCode: 8,  description: null },
  { id: 37, contentId: '126887',  name: '선돌 전망대',           areaCode: 32, sigunguCode: 8,  description: null },
  { id: 38, contentId: '2700323', name: '젊은달와이파크',        areaCode: 32, sigunguCode: 8,  description: null },
  { id: 39, contentId: '779594',  name: '한반도지형전망대',      areaCode: 32, sigunguCode: 8,  description: null },
  { id: 40, contentId: '770251',  name: '한반도뗏목마을',        areaCode: 32, sigunguCode: 8,  description: null },
  { id: 41, contentId: '2616104', name: '요선암 돌개구멍',       areaCode: 32, sigunguCode: 8,  description: null },
  { id: 42, contentId: '125906',  name: '법주사',                areaCode: 33, sigunguCode: 3,  description: '속리산 법주사는 재위 말년 피부병 치료를 위해 세조가 찾았던 유서 깊은 사찰이다. 이동 중 가마가 걸리지 않게 가지를 들어 올려 정이품 벼슬을 받았다는 \'정이품송\' 설화의 배경지이기도 하다. 국보 팔상전 등 화려한 불교 유산이 가득한 이곳은, 조카를 밀어냈다는 죄책감 속에서 불교에 의지하고자 했던 세조의 복잡한 내면과 신앙심이 깃든 공간이다.' },
  { id: 43, contentId: '2671791', name: '말티재 전망대',         areaCode: 33, sigunguCode: 3,  description: null },
  { id: 44, contentId: '125989',  name: '보은 삼년산성',         areaCode: 33, sigunguCode: 3,  description: null },
  { id: 45, contentId: '2650370', name: '속리산 세조길',         areaCode: 33, sigunguCode: 3,  description: null },
  { id: 46, contentId: '126009',  name: '정이품송',              areaCode: 33, sigunguCode: 3,  description: null },
  { id: 47, contentId: '2782912', name: '속리산테마파크 모노레일', areaCode: 33, sigunguCode: 3, description: null },
  { id: 48, contentId: '129689',  name: '속리산조각공원',        areaCode: 33, sigunguCode: 3,  description: null },
  { id: 49, contentId: '125552',  name: '서오릉',                    areaCode: 31, sigunguCode: 2,  description: '서오릉 내 창릉은 조선 제8대 국왕 예종과 안순왕후 권씨가 모셔진 부부 능이다. 세조의 뒤를 이어 왕위에 오른 예종은 법전을 정비하는 등 개혁을 꿈꿨으나, 재위 14개월 만인 20세의 젊은 나이에 요절하였다. 서오릉에서 가장 깊숙한 곳에 자리한 창릉은 울창한 숲길을 걸으며 짧지만 강렬했던 청년 왕 예종의 숨결을 조용히 추모하기 좋은 곳이다.' },
  { id: 50, contentId: '125562',  name: '행주산성',                  areaCode: 31, sigunguCode: 2,  description: null },
  { id: 51, contentId: '2554262', name: '한국항공대학교 항공우주박물관', areaCode: 31, sigunguCode: 2,  description: null },
  { id: 52, contentId: '3102071', name: '은평한옥마을',              areaCode: 1,  sigunguCode: 22, description: null },
  { id: 53, contentId: '2661736', name: '행주산성 역사공원',         areaCode: 31, sigunguCode: 2,  description: null },
  { id: 54, contentId: '127219',  name: '수국사',                    areaCode: 1,  sigunguCode: 22, description: null },
  { id: 55, contentId: '128871',  name: '흥국사',                    areaCode: 31, sigunguCode: 2,  description: null },
  { id: 56, contentId: '126517',  name: '서울문묘와성균관',          areaCode: 1,  sigunguCode: 23, description: '서울 문묘와 성균관은 성종이 추구한 문치주의 정치의 정수가 서린 곳이다. 성종은 유교 통치 체제를 확립하고자 성균관을 대대적으로 중축하고, 최초의 도서관인 \'존경각\'을 지어 인재 양성의 기틀을 다졌다. 또한 친히 문묘를 찾아 제사를 올리고 학문을 토론하며 위축되었던 유학 학풍을 일으켜 세웠다. 유교 국가를 완성한 성종의 정치 철학과 숨결이 깃든 공간이다.' },
  { id: 57, contentId: '127642',  name: '창덕궁 후원',               areaCode: 1,  sigunguCode: 23, description: null },
  { id: 58, contentId: '126510',  name: '종묘',                      areaCode: 1,  sigunguCode: 23, description: '현종 시대를 뒤흔든 예송논쟁은 단순한 말다툼이 아니라, 왕실의 의례와 국왕의 정통성을 바로 세우기 위한 치열한 붕당정치의 결과물이었다. 조선 왕조의 역대 왕과 왕비의 신주를 모신 유교 사당인 종묘는 왕권을 지키고 국가 체제를 정비하고자 신하들과 치열하게 논쟁했던 현종의 치세를 되돌아보게 한다.' },
  { id: 59, contentId: '1941440', name: '아라리오뮤지엄 인 스페이스', areaCode: 1,  sigunguCode: 23, description: null },
  { id: 60, contentId: '1934593', name: '국립현대미술관 서울',       areaCode: 1,  sigunguCode: 23, description: null },
  { id: 61, contentId: '126537',  name: '북촌한옥마을',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 62, contentId: '129501',  name: '낙산공원',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 63, contentId: '2765222', name: '연산군유배지',              areaCode: 2,  sigunguCode: 1,  description: '인천 강화군 교동도의 연산군 유배지는 중종반정으로 폐위된 연산군이 생의 마지막을 보낸 비극적인 공간이다. 화려한 궁궐을 떠난 그는 사방이 가시울타리로 막힌 좁은 집에 갇히는 위리안치 형벌을 받았다. 철저히 고립된 채 신음하던 연산군은 유배 두 달 만에 이곳에서 쓸쓸히 숨을 거두었다. 권력의 허무함과 폭군의 비참한 말로를 생생히 보여주는 유적지다.' },
  { id: 64, contentId: '2492108', name: '교동대룡시장',              areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 65, contentId: '2657249', name: '교동제비집',                areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 66, contentId: '1953948', name: '교동향교',                  areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 67, contentId: '3061177', name: '강화 화개산모노레일',       areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 68, contentId: '2552255', name: '해든뮤지움',                areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 69, contentId: '2657245', name: '교동도 망향대',             areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 70, contentId: '126525',  name: '중종정릉',                  areaCode: 1,  sigunguCode: 1,  description: '정릉은 조선 제11대 국왕 중종이 홀로 묻힌 단독 능이다. 본래 다른 곳에 있던 능을 세 번째 왕비인 문정왕후가 사후에 나란히 묻히고자 현재의 자리로 이장했다. 그러나 정작 이장한 자리가 침수가 잦아 문정왕후는 함께 묻히지 못했고, 결국 중종만 쓸쓸히 남게 되었다. 도심 속 울창한 숲길을 걸으며 중종의 마지막 흔적을 마주할 수 있는 유적지다.' },
  { id: 71, contentId: '2761709', name: '대한불교조계종 봉은사',     areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 72, contentId: '3074742', name: '마이아트뮤지엄',            areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 73, contentId: '130226',  name: '포스코미술관',              areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 74, contentId: '130926',  name: '도산공원 도산안창호기념관', areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 75, contentId: '126747',  name: '남산골한옥마을',            areaCode: 1,  sigunguCode: 24, description: null },
  { id: 76, contentId: '126491',  name: '장충단공원',                areaCode: 1,  sigunguCode: 24, description: null },
  { id: 77, contentId: '125551',  name: '서삼릉',                    areaCode: 31, sigunguCode: 2,  description: '고양 서삼릉 효릉은 지극한 효심을 지녔으나 재위 9개월 만에 승하한 비운의 왕, 조선 제12대 인종과 인성왕후가 잠든 쌍릉이다. 아버지를 향한 슬픔으로 건강을 해쳐 이른 나이에 세상을 떠난 인종의 효심을 기려 \'효릉\'이라 명명되었다. 오랜 비공개 기간을 거쳐 최근 전면 개방되어 그 애틋한 숨결을 느낄 수 있다.' },
  { id: 78, contentId: '128138',  name: '원당종마목장',              areaCode: 31, sigunguCode: 2,  description: null },
  { id: 79, contentId: '127877',  name: '쥬쥬랜드',                  areaCode: 31, sigunguCode: 2,  description: null },
  { id: 80, contentId: '125552',  name: '서오릉',                    areaCode: 31, sigunguCode: 2,  description: null },
  { id: 81, contentId: '127197',  name: '일산호수공원',              areaCode: 31, sigunguCode: 2,  description: null },
  { id: 82, contentId: '2892126', name: '고양아람누리 아람미술관',   areaCode: 31, sigunguCode: 2,  description: null },
  { id: 83, contentId: '2568681', name: '공릉천',                    areaCode: 31, sigunguCode: 2,  description: null },
  { id: 84, contentId: '2546181', name: '회암사지박물관',            areaCode: 31, sigunguCode: 18, description: '회암사지 박물관은 명종 시대 권력의 정점이었던 문정왕후가 불교 중흥을 이끈 조선 최대 왕실 원찰 터에 세워진 박물관이다. 1565년 문정왕후는 명종의 무병장수를 기원하는 거대한 무차대재를 이곳에서 열었다. 사후 유림에 의해 사찰이 소실되는 수난을 겪었으나, 명종 시대 왕실 전용 청기와와 도자기 등 당대 정쟁과 미술의 정수를 팩트로 증명하는 유물 전시관이다.' },
  { id: 85, contentId: '3345603', name: '양주관아지',                areaCode: 31, sigunguCode: 18, description: null },
  { id: 86, contentId: '2790984', name: '양주시립장욱진미술관',      areaCode: 31, sigunguCode: 18, description: null },
  { id: 87, contentId: '2670558', name: '나리농원',                  areaCode: 31, sigunguCode: 18, description: null },
  { id: 88, contentId: '130742',  name: '조명박물관',                areaCode: 31, sigunguCode: 18, description: null },
  { id: 89, contentId: '129194',  name: '가나아트파크',              areaCode: 31, sigunguCode: 18, description: null },
  { id: 90, contentId: '2751265', name: '옥정호수공원',              areaCode: 31, sigunguCode: 18, description: null },
  { id: 91, contentId: '2733962', name: '인왕산 수성동계곡',         areaCode: 1,  sigunguCode: 23, description: '전후 복구에 힘쓰던 광해군은 왕권을 강화하고 국력을 과시하기 위해 인경궁 등 대규모 궁궐 건축을 추진했다. 이 계곡은 당시 궁궐을 짓기 위해 거대한 암석들을 채석했던 흔적이 남아있는 곳이다. 대동법과 중립외교라는 업적 이면에 존재했던 대공사의 흔적을 아름다운 자연 속에서 찾아볼 수 있다.' },
  { id: 92, contentId: '125449',  name: '남한산성 도립공원',         areaCode: 31, sigunguCode: 5,  description: '인조반정으로 즉위한 인조가 치열한 국제 정세 속에서 정묘호란과 병자호란을 겪으며 고뇌했던 피난처이다. 청나라 군대에 맞서 47일 동안 끈질기게 항전했던 서사가 성곽 굽이마다 서려 있다. 비록 삼전도의 아픔으로 이어졌으나, 국방력 강화를 위해 노력했던 인조의 흔적이 가장 짙게 배어있는 장소이다.' },
  { id: 93, contentId: '127110',  name: '강진 전라변영성',           areaCode: 38, sigunguCode: 1,  description: '강력한 군사력을 키워 청나라를 정벌하려던 효종의 북벌 의지가 투영된 국방 유적지이다. 효종은 군제 개혁을 단행하던 중, 조선에 표착한 네덜란드인 하멜 일행을 이곳에 배치하여 서양식 화포 기술을 습득하도록 지시했다. 나라의 자존심을 세우고 국력을 강화하려 했던 효종의 실리적 노력을 엿볼 수 있다.' },
  { id: 94, contentId: '125550',  name: '북한산성',                  areaCode: 31, sigunguCode: 2,  description: '강력한 절대왕권을 확립한 숙종의 압도적인 추진력을 체감할 수 있는 웅장한 성곽이다. 임진왜란과 병자호란을 거치며 수십 년간 논쟁만 무성했던 수도 방어 체제 구축을 숙종은 단 6개월 만에 속전속결로 완공시켰다. 환국정치로 다진 강력한 왕권이 민생 안정과 튼튼한 국방으로 이어졌음을 보여주는 명백한 증거이다.' },
  { id: 95, contentId: '2606158', name: '창경궁 명정전',             areaCode: 1,  sigunguCode: 23, description: '치열한 당쟁 속에서 왕위에 오른 경종이 세자 시절 아버지 숙종을 대신해 대리청정을 하며 국정을 돌보았던 역사의 무대이다. 또한 즉위 후 신하들의 하례를 받으며 당당한 조선의 국왕임을 공표하고 왕권을 행사했던 공식적인 공간이기도 하다. 조선에 현존하는 가장 오래된 정전인 이곳에서 묵묵히 통치를 이어간 경종의 군주로서의 책임감을 엿볼 수 있다.' },
  { id: 96, contentId: '126517',  name: '성균관',                    areaCode: 1,  sigunguCode: 23, description: '붕당정치의 폐단을 막기 위해 평생을 바친 영조의 강력한 개혁 의지를 볼 수 있는 곳이다. 영조는 성균관 입구에 신하들의 화합을 강조하는 \'탕평비\'를 직접 세우고 세자들에게 정치를 가르쳤다. 학문의 전당인 성균관에서 인재를 기르고 능력 중심의 탕평책을 펼치고자 했던 영조의 통치 철학과 조선 후기 탕평 정치의 정수를 체감하기 좋다.' },
  { id: 97, contentId: '125555',  name: '수원 화성',                 areaCode: 31, sigunguCode: 13, description: '정조의 개혁 사상과 조선 후기 건축 기술의 정수가 집약된 역사적 현장이다. 정조는 사도세자의 묘를 옮기며 이곳에 신도시를 건설하고, 친위부대인 장용영을 배치해 강력한 왕권을 다졌다. 실학을 바탕으로 국방과 상업의 중심지를 개척하며, 새로운 조선을 꿈꾸었던 \'개혁 군주\' 정조의 찬란했던 업적과 비전이 고스란히 남아있다.' },
  { id: 98, contentId: '827642',  name: '헌인릉',                    areaCode: 1,  sigunguCode: 15, description: '안동 김씨 등 외척 세력이 권력을 장악했던 세도정치기 속에서 비운의 침체기를 겪은 순조의 마지막 안식처이다. 비록 왕권이 약화되는 혼란기였으나 공노비를 해방하는 등 사회적 모순을 해결하려 노력했던 순조의 자취가 서려 있다. 순조와 정비 순원왕후가 합장된 이 고즈넉한 능은 격변하는 정세 속에서 고군분투했던 국왕의 고뇌를 조용히 돌아보게 한다.' },
  { id: 99, contentId: '1604941', name: '창덕궁 낙선재',             areaCode: 1,  sigunguCode: 23, description: '조선 역대 최연소인 8세의 나이로 즉위한 헌종이 세도정치의 틈바구니 속에서 마련한 자신만의 안식처이다. 단청을 칠하지 않아 소박하고 담백한 미학을 자랑하며, 평소 서화와 조각을 사랑했던 헌종의 뛰어난 예술적 안목이 깊게 배어있다. 정치를 벗어나 학문과 서재 겸 휴식 공간으로 직접 짓게 한 이 건물에서 어린 왕의 숨결을 그대로 느낄 수 있다.' },
  { id: 100, contentId: '231899',  name: '용흥궁',                    areaCode: 2,  sigunguCode: 1,  description: '강화도에서 평민처럼 농사를 지으며 살다가 사도세자의 후손으로서 왕위에 오른 철종의 잠저이다. 왕족이었으나 유배지에서 비운의 삶을 살았던 \'강화도령\' 원범의 독특한 서사가 집터 곳곳에 남아있다. 세도정치의 심화로 삼정의 문란이 극에 달하자 삼정이정청을 설치해 개혁을 시도하려 했던 철종의 인간적인 고뇌와 그의 소박한 뿌리를 대변하는 장소이다.' },
  { id: 101, contentId: '2756396', name: '덕수궁 석조전',             areaCode: 1,  sigunguCode: 24, description: '급변하는 국제 정세 속에서 근대 국가로의 발전을 도모했던 고종의 굳은 의지가 투영된 웅장한 건축물이다. 고종이 대한제국을 선포한 후 황궁의 정전으로 사용하기 위해 지은 신고전주의 양식의 서양식 석조건물이다. 외세의 압박 속에서도 광무개혁을 추진하며 자주독립국가로서 나라의 격을 높이고자 했던 고종황제의 고독함과 근대화 열망이 서려 있다.' },
  { id: 102, contentId: '129811',  name: '국립고궁박물관',            areaCode: 1,  sigunguCode: 23, description: '대한제국의 마지막 황제, 순종의 실제 삶과 흔적을 유물로 가장 가깝게 만날 수 있는 공간이다. 순종황제가 직접 타고 다녔던 어차(황제 전용 리무진)와 창덕궁에서 사용했던 황실 당구대, 가구 등이 전시되어 있다. 조선 왕조의 마지막 마침표를 찍으며 황실의 자존심을 지키고자 했던 순종의 비운의 역사와 황실 문화가 생생히 살아있다.' },
  { id: 103, contentId: '1254680', name: '갑곶돈대',                  areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 104, contentId: '129694',  name: '병영성홍교',                areaCode: 38, sigunguCode: 1,  description: null },
  { id: 105, contentId: '2650800', name: '사의재저잣거리',            areaCode: 38, sigunguCode: 1,  description: null },
  { id: 106, contentId: '127110',  name: '강진 전라병영성',           areaCode: 38, sigunguCode: 1,  description: null },
  { id: 107, contentId: '128819',  name: '대한성공회 강화성당',       areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 108, contentId: '125564',  name: '강화산성',                  areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 109, contentId: '129810',  name: '강화역사박물관',            areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 110, contentId: '2657495', name: '강화전쟁박물관',            areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 111, contentId: '126484',  name: '경희궁',                    areaCode: 1,  sigunguCode: 23, description: null },
  { id: 112, contentId: '127184',  name: '고려궁지',                  areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 113, contentId: '2662855', name: '광교호수공원',              areaCode: 31, sigunguCode: 13, description: null },
  { id: 114, contentId: '775394',  name: '광화문광장',                areaCode: 1,  sigunguCode: 23, description: null },
  { id: 115, contentId: '2608977', name: '국립민속박물관',            areaCode: 1,  sigunguCode: 23, description: null },
  { id: 116, contentId: '298106',  name: '금곡사(강진)',              areaCode: 38, sigunguCode: 1,  description: null },
  { id: 117, contentId: '129501',  name: '낙산공원',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 118, contentId: '132226',  name: '낙원 악기상가',             areaCode: 1,  sigunguCode: 23, description: null },
  { id: 119, contentId: '126747',  name: '남산골한옥마을',            areaCode: 1,  sigunguCode: 24, description: null },
  { id: 120, contentId: '126485',  name: '남산공원(서울)',            areaCode: 1,  sigunguCode: 24, description: null },
  { id: 121, contentId: '2751248', name: '남한산성행궁',              areaCode: 31, sigunguCode: 5,  description: null },
  { id: 122, contentId: '2783558', name: '홍건익 가옥',               areaCode: 1,  sigunguCode: 23, description: null },
  { id: 123, contentId: '126487',  name: '마로니에공원',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 124, contentId: '1849416', name: '대한민국역사박물관',        areaCode: 1,  sigunguCode: 23, description: null },
  { id: 125, contentId: '127425',  name: '독립문',                    areaCode: 1,  sigunguCode: 14, description: null },
  { id: 126, contentId: '2470006', name: '동대문디자인플라자',        areaCode: 1,  sigunguCode: 24, description: null },
  { id: 127, contentId: '1906334', name: '동대문역사문화공원',        areaCode: 1,  sigunguCode: 24, description: null },
  { id: 128, contentId: '3351831', name: '만석공원',                  areaCode: 31, sigunguCode: 13, description: null },
  { id: 129, contentId: '2514045', name: '윤봉길의사기념관',          areaCode: 1,  sigunguCode: 15, description: null },
  { id: 130, contentId: '126517',  name: '서울 문묘',                 areaCode: 1,  sigunguCode: 23, description: null },
  { id: 131, contentId: '2613658', name: '방화수류정',                areaCode: 31, sigunguCode: 13, description: null },
  { id: 132, contentId: '1198901', name: '배재학당역사박물관',        areaCode: 1,  sigunguCode: 24, description: null },
  { id: 133, contentId: '130473',  name: '백범김구기념관',            areaCode: 1,  sigunguCode: 21, description: null },
  { id: 134, contentId: '128952',  name: '강진 병영마을 옛 담장',    areaCode: 38, sigunguCode: 1,  description: null },
  { id: 135, contentId: '3433766', name: '석문공원',                  areaCode: 38, sigunguCode: 1,  description: null },
  { id: 136, contentId: '126504',  name: '봉은사(서울)',              areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 137, contentId: '126537',  name: '북촌한옥마을',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 138, contentId: '1196886', name: '북한산둘레길 5구간',        areaCode: 1,  sigunguCode: 22, description: null },
  { id: 139, contentId: '127220',  name: '북한산국립공원',            areaCode: 1,  sigunguCode: 3,  description: null },
  { id: 140, contentId: '128887',  name: '흥국사(고양)',              areaCode: 31, sigunguCode: 2,  description: null },
  { id: 141, contentId: '127558',  name: '진관사',                    areaCode: 1,  sigunguCode: 22, description: null },
  { id: 142, contentId: '127557',  name: '삼천사',                    areaCode: 1,  sigunguCode: 22, description: null },
  { id: 143, contentId: '2992891', name: '사직단',                    areaCode: 1,  sigunguCode: 23, description: null },
  { id: 144, contentId: '402994',  name: '삼청동 문화거리',           areaCode: 1,  sigunguCode: 23, description: null },
  { id: 145, contentId: '130152',  name: '서대문형무소역사관',        areaCode: 1,  sigunguCode: 14, description: null },
  { id: 146, contentId: '3019162', name: '서순라길',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 147, contentId: '2598331', name: '서울광장',                  areaCode: 1,  sigunguCode: 24, description: null },
  { id: 148, contentId: '2638478', name: '서울도시건축전시관',        areaCode: 1,  sigunguCode: 24, description: null },
  { id: 149, contentId: '128611',  name: '서울숲',                    areaCode: 1,  sigunguCode: 16, description: null },
  { id: 150, contentId: '130071',  name: '서울시립미술관 본관',       areaCode: 1,  sigunguCode: 24, description: null },
  { id: 151, contentId: '130361',  name: '서울역사박물관',            areaCode: 1,  sigunguCode: 23, description: null },
  { id: 152, contentId: '3351700', name: '서초문화예술공원',          areaCode: 1,  sigunguCode: 15, description: null },
  { id: 153, contentId: '2037020', name: '서촌마을',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 154, contentId: '126525',  name: '선릉과 정릉',               areaCode: 1,  sigunguCode: 1,  description: null },
  { id: 155, contentId: '2930901', name: '성수동 카페거리',           areaCode: 1,  sigunguCode: 16, description: null },
  { id: 156, contentId: '2553876', name: '세운상가',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 157, contentId: '2992822', name: '세종마을 음식문화거리',     areaCode: 1,  sigunguCode: 23, description: null },
  { id: 158, contentId: '638913',  name: '수원박물관',                areaCode: 31, sigunguCode: 13, description: null },
  { id: 159, contentId: '3080477', name: '수원전통문화관',            areaCode: 31, sigunguCode: 13, description: null },
  { id: 160, contentId: '1131275', name: '매헌시민의 숲',             areaCode: 1,  sigunguCode: 15, description: null },
  { id: 161, contentId: '129610',  name: '강화 연미정',               areaCode: 2,  sigunguCode: 1,  description: null },
  { id: 162, contentId: '3056152', name: '열린송현 녹지광장',         areaCode: 1,  sigunguCode: 23, description: null },
  { id: 163, contentId: '127111',  name: '강진영랑생가',              areaCode: 38, sigunguCode: 1,  description: null },
  { id: 164, contentId: '2757831', name: '우면산자연생태공원',        areaCode: 1,  sigunguCode: 15, description: null },
  { id: 165, contentId: '2993372', name: '윤동주 하숙집 터',          areaCode: 1,  sigunguCode: 23, description: null },
  { id: 166, contentId: '2739477', name: '윤동주문학관',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 167, contentId: '2764323', name: '은평역사한옥박물관',        areaCode: 1,  sigunguCode: 22, description: null },
  { id: 168, contentId: '2724392', name: '은평한옥마을',              areaCode: 1,  sigunguCode: 22, description: null },
  { id: 169, contentId: '3044977', name: '이상의집',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 170, contentId: '1102845', name: '이화벽화마을',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 171, contentId: '2650046', name: '익선동 한옥거리',           areaCode: 1,  sigunguCode: 23, description: null },
  { id: 172, contentId: '132219',  name: '인사동 문화의 거리',        areaCode: 1,  sigunguCode: 23, description: null },
  { id: 173, contentId: '2764331', name: '인왕산 국사당',             areaCode: 1,  sigunguCode: 23, description: null },
  { id: 174, contentId: '130227',  name: '일민미술관',                areaCode: 1,  sigunguCode: 23, description: null },
  { id: 175, contentId: '127030',  name: '장경사',                    areaCode: 31, sigunguCode: 5,  description: null },
  { id: 176, contentId: '2778454', name: '정동길',                    areaCode: 1,  sigunguCode: 24, description: null },
  { id: 177, contentId: '2739454', name: '박노수미술관',              areaCode: 1,  sigunguCode: 23, description: null },
  { id: 178, contentId: '1625025', name: '지수당',                    areaCode: 1,  sigunguCode: 23, description: null },
  { id: 179, contentId: '127558',  name: '진관사',                    areaCode: 1,  sigunguCode: 22, description: null },
  { id: 180, contentId: '1605036', name: '창경궁 대온실',             areaCode: 1,  sigunguCode: 23, description: null },
  { id: 181, contentId: '1605009', name: '창경궁 홍화문',             areaCode: 1,  sigunguCode: 23, description: null },
  { id: 182, contentId: '127642',  name: '창덕궁 후원',               areaCode: 1,  sigunguCode: 23, description: null },
  { id: 183, contentId: '2565510', name: '청계광장',                  areaCode: 1,  sigunguCode: 24, description: null },
  { id: 184, contentId: '1957671', name: '종로 청계 관광특구',        areaCode: 1,  sigunguCode: 23, description: null },
  { id: 185, contentId: '690984',  name: '청와대 사랑채',             areaCode: 1,  sigunguCode: 23, description: null },
  { id: 186, contentId: '2762885', name: '청운공원',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 187, contentId: '126944',  name: '침괘정',                    areaCode: 31, sigunguCode: 5,  description: null },
  { id: 188, contentId: '129534',  name: '탑골공원',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 189, contentId: '1590323', name: '통인시장',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 190, contentId: '264386',  name: '팔달문',                    areaCode: 31, sigunguCode: 13, description: null },
  { id: 191, contentId: '1939691', name: '한양도성박물관',            areaCode: 1,  sigunguCode: 23, description: null },
  { id: 192, contentId: '2745995', name: '행궁동 벽화마을',           areaCode: 31, sigunguCode: 13, description: null },
  { id: 193, contentId: '129437',  name: '화성행궁',                  areaCode: 31, sigunguCode: 13, description: null },
  { id: 194, contentId: '264394',  name: '화홍문',                    areaCode: 31, sigunguCode: 13, description: null },
  { id: 195, contentId: '1604450', name: '황학정',                    areaCode: 1,  sigunguCode: 23, description: null },
  { id: 196, contentId: '127643',  name: '서울 효창공원',             areaCode: 1,  sigunguCode: 21, description: null },
  { id: 197, contentId: '126514',  name: '흥인지문',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 198, contentId: '132183',  name: '광장시장',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 199, contentId: '126522',  name: '동관왕묘',                  areaCode: 1,  sigunguCode: 23, description: null },
  { id: 200, contentId: '1754832', name: '서울풍물시장',              areaCode: 1,  sigunguCode: 11, description: null },
  { id: 201, contentId: '2515265', name: '강진 백운동별서정원',       areaCode: 38, sigunguCode: 1,  description: null },
  { id: 202, contentId: '1624958', name: '남한산성 수어장대',         areaCode: 31, sigunguCode: 5,  description: null },
  { id: 203, contentId: '630741',  name: '경안천 습지생태공원',       areaCode: 31, sigunguCode: 5,  description: null },
  { id: 204, contentId: '612305',  name: '남한산성 전통음식마을',     areaCode: 31, sigunguCode: 5,  description: null },
];

async function main() {
  for (const king of kings) {
    await prisma.king.upsert({
      where: { id: king.id },
      update: {
        name: king.name,
        orderNumber: king.orderNumber,
        shortDescription: king.shortDescription,
        description: king.description,
      },
      create: { ...king, imageUrl: null },
    });
  }

  for (const { kingId, tags } of kingTags) {
    await prisma.kingTag.upsert({
      where: { kingId },
      update: {
        tag1: tags[0] ?? null,
        tag2: tags[1] ?? null,
        tag3: tags[2] ?? null,
        tag4: tags[3] ?? null,
        tag5: tags[4] ?? null,
        tag6: tags[5] ?? null,
      },
      create: {
        kingId,
        tag1: tags[0] ?? null,
        tag2: tags[1] ?? null,
        tag3: tags[2] ?? null,
        tag4: tags[3] ?? null,
        tag5: tags[4] ?? null,
        tag6: tags[5] ?? null,
      },
    });
  }

  for (const spot of spots) {
    await prisma.spot.upsert({
      where: { id: spot.id },
      update: {
        contentId: spot.contentId,
        name: spot.name,
        areaCode: spot.areaCode,
        sigunguCode: spot.sigunguCode,
        description: spot.description,
      },
      create: {
        id: spot.id,
        contentId: spot.contentId,
        name: spot.name,
        areaCode: spot.areaCode,
        sigunguCode: spot.sigunguCode,
        description: spot.description,
      },
    });
  }

  const kingSpots = [
    { kingId: 1,  spotId: 1   },
    { kingId: 2,  spotId: 8   },
    { kingId: 3,  spotId: 15  },
    { kingId: 4,  spotId: 22  },
    { kingId: 5,  spotId: 29  },
    { kingId: 6,  spotId: 36  },
    { kingId: 7,  spotId: 43  },
    { kingId: 8,  spotId: 50  },
    { kingId: 9,  spotId: 57  },
    { kingId: 10, spotId: 64  },
    { kingId: 11, spotId: 71  },
    { kingId: 12, spotId: 78  },
    { kingId: 13, spotId: 85  },
    { kingId: 14, spotId: 14  },
    { kingId: 15, spotId: 15  },
    { kingId: 16, spotId: 16  },
    { kingId: 17, spotId: 17  },
    { kingId: 18, spotId: 18  },
    { kingId: 19, spotId: 19  },
    { kingId: 20, spotId: 20  },
    { kingId: 21, spotId: 21  },
    { kingId: 22, spotId: 22  },
    { kingId: 23, spotId: 23  },
    { kingId: 24, spotId: 24  },
    { kingId: 25, spotId: 25  },
    { kingId: 26, spotId: 26  },
    { kingId: 27, spotId: 27  },
  ];

  await prisma.kingSpot.createMany({
    data: kingSpots,
    skipDuplicates: true,
  });

  const routes = [
    { id: 1,  kingId: 1,  name: '태조 루트 1',   tag: '#자전거 추천',    estimatedMinutes: 120 },
    { id: 2,  kingId: 1,  name: '태조 루트 2',   tag: '#도보 추천',      estimatedMinutes: 240 },
    { id: 3,  kingId: 2,  name: '정종 루트 1',   tag: '#자전거 추천',    estimatedMinutes: 150 },
    { id: 4,  kingId: 2,  name: '정종 루트 2',   tag: '#도보 추천',      estimatedMinutes: 180 },
    { id: 5,  kingId: 3,  name: '태종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 6,  kingId: 3,  name: '태종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 7,  kingId: 4,  name: '세종 루트 1',   tag: '#도보 추천',      estimatedMinutes: 180 },
    { id: 8,  kingId: 4,  name: '세종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 150 },
    { id: 9,  kingId: 5,  name: '문종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 240 },
    { id: 10, kingId: 5,  name: '문종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 210 },
    { id: 11, kingId: 6,  name: '단종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 240 },
    { id: 12, kingId: 6,  name: '단종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 420 },
    { id: 13, kingId: 7,  name: '세조 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 270 },
    { id: 14, kingId: 7,  name: '세조 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 270 },
    { id: 15, kingId: 8,  name: '예종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 16, kingId: 8,  name: '예종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 17, kingId: 9,  name: '성종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 300 },
    { id: 18, kingId: 9,  name: '성종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 390 },
    { id: 19, kingId: 10, name: '연산군 루트 1', tag: '#대중교통 추천',  estimatedMinutes: 270 },
    { id: 20, kingId: 10, name: '연산군 루트 2', tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 21, kingId: 11, name: '중종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 300 },
    { id: 22, kingId: 11, name: '중종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 23, kingId: 12, name: '인종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 300 },
    { id: 24, kingId: 12, name: '인종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 25, kingId: 13, name: '명종 루트 1',   tag: '#대중교통 추천',  estimatedMinutes: 300 },
    { id: 26, kingId: 13, name: '명종 루트 2',   tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 27, kingId: 14, name: '선조 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 28, kingId: 14, name: '선조 루트',     tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 29, kingId: 15, name: '광해군 루트',   tag: '#도보 추천',      estimatedMinutes: 270 },
    { id: 30, kingId: 15, name: '광해군 루트',   tag: '#자전거 추천',    estimatedMinutes: 360 },
    { id: 31, kingId: 16, name: '인조 루트',     tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 32, kingId: 16, name: '인조 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 33, kingId: 17, name: '효종 루트',     tag: '#자전거 추천',    estimatedMinutes: 270 },
    { id: 34, kingId: 17, name: '효종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 35, kingId: 18, name: '현종 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 36, kingId: 18, name: '현종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 270 },
    { id: 37, kingId: 19, name: '숙종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 38, kingId: 19, name: '숙종 루트',     tag: '#도보 추천',      estimatedMinutes: 330 },
    { id: 39, kingId: 20, name: '경종 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 40, kingId: 20, name: '경종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 330 },
    { id: 41, kingId: 21, name: '영조 루트',     tag: '#자전거 추천',    estimatedMinutes: 300 },
    { id: 42, kingId: 21, name: '영조 루트',     tag: '#도보 추천',      estimatedMinutes: 330 },
    { id: 43, kingId: 22, name: '정조 루트',     tag: '#도보 추천',      estimatedMinutes: 330 },
    { id: 44, kingId: 22, name: '정조 루트',     tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 45, kingId: 23, name: '순조 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 46, kingId: 23, name: '순조 루트',     tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 47, kingId: 24, name: '헌종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 360 },
    { id: 48, kingId: 24, name: '헌종 루트',     tag: '#도보 추천',      estimatedMinutes: 330 },
    { id: 49, kingId: 25, name: '철종 루트',     tag: '#자전거 추천',    estimatedMinutes: 330 },
    { id: 50, kingId: 25, name: '철종 루트',     tag: '#도보 추천',      estimatedMinutes: 270 },
    { id: 51, kingId: 26, name: '고종 루트',     tag: '#도보 추천',      estimatedMinutes: 300 },
    { id: 52, kingId: 26, name: '고종 루트',     tag: '#대중교통 추천',  estimatedMinutes: 390 },
    { id: 53, kingId: 27, name: '순종 루트',     tag: '#도보 추천',      estimatedMinutes: 330 },
    { id: 54, kingId: 27, name: '순종 루트',     tag: '#자전거 추천',    estimatedMinutes: 390 },
  ];

  for (const route of routes) {
    await prisma.route.upsert({
      where: { id: route.id },
      update: {
        kingId: route.kingId,
        name: route.name,
        tag: route.tag,
        estimatedMinutes: route.estimatedMinutes,
      },
      create: route,
    });
  }

  await prisma.routeSpot.deleteMany({});

  const s = (id) => id >= 13 ? id - 1 : id; // spotId 보정 함수

  const routeSpots = [
    // route 1
    { routeId: 1,  spotId: s(6),   orderNumber: 1 },
    { routeId: 1,  spotId: s(2),   orderNumber: 2 },
    { routeId: 1,  spotId: s(1),   orderNumber: 3 },
    { routeId: 1,  spotId: s(3),   orderNumber: 4 },
    // route 2
    { routeId: 2,  spotId: s(4),   orderNumber: 1 },
    { routeId: 2,  spotId: s(1),   orderNumber: 2 },
    { routeId: 2,  spotId: s(5),   orderNumber: 3 },
    { routeId: 2,  spotId: s(7),   orderNumber: 4 },
    // route 3
    { routeId: 3,  spotId: s(9),   orderNumber: 1 },
    { routeId: 3,  spotId: s(8),   orderNumber: 2 },
    { routeId: 3,  spotId: s(10),  orderNumber: 3 },
    { routeId: 3,  spotId: s(11),  orderNumber: 4 },
    // route 4 (원본 spotId 12와 13이 보정 후 둘 다 12가 되어 13→12만 유지)
    { routeId: 4,  spotId: s(14),  orderNumber: 1 },
    { routeId: 4,  spotId: s(13),  orderNumber: 4 },
    { routeId: 4,  spotId: s(8),   orderNumber: 3 },
    // route 5
    { routeId: 5,  spotId: s(20),  orderNumber: 1 },
    { routeId: 5,  spotId: s(15),  orderNumber: 2 },
    { routeId: 5,  spotId: s(16),  orderNumber: 3 },
    { routeId: 5,  spotId: s(17),  orderNumber: 4 },
    // route 6
    { routeId: 6,  spotId: s(19),  orderNumber: 1 },
    { routeId: 6,  spotId: s(18),  orderNumber: 2 },
    { routeId: 6,  spotId: s(15),  orderNumber: 3 },
    { routeId: 6,  spotId: s(21),  orderNumber: 4 },
    // route 7
    { routeId: 7,  spotId: s(26),  orderNumber: 1 },
    { routeId: 7,  spotId: s(23),  orderNumber: 2 },
    { routeId: 7,  spotId: s(22),  orderNumber: 3 },
    { routeId: 7,  spotId: s(28),  orderNumber: 4 },
    // route 8
    { routeId: 8,  spotId: s(27),  orderNumber: 1 },
    { routeId: 8,  spotId: s(24),  orderNumber: 2 },
    { routeId: 8,  spotId: s(22),  orderNumber: 3 },
    { routeId: 8,  spotId: s(25),  orderNumber: 4 },
    // route 9
    { routeId: 9,  spotId: s(29),  orderNumber: 1 },
    { routeId: 9,  spotId: s(34),  orderNumber: 2 },
    { routeId: 9,  spotId: s(31),  orderNumber: 3 },
    { routeId: 9,  spotId: s(33),  orderNumber: 4 },
    // route 10
    { routeId: 10, spotId: s(30),  orderNumber: 1 },
    { routeId: 10, spotId: s(35),  orderNumber: 2 },
    { routeId: 10, spotId: s(32),  orderNumber: 3 },
    { routeId: 10, spotId: s(29),  orderNumber: 4 },
    // route 11
    { routeId: 11, spotId: s(38),  orderNumber: 1 },
    { routeId: 11, spotId: s(36),  orderNumber: 2 },
    { routeId: 11, spotId: s(37),  orderNumber: 3 },
    // route 12
    { routeId: 12, spotId: s(42),  orderNumber: 1 },
    { routeId: 12, spotId: s(39),  orderNumber: 2 },
    { routeId: 12, spotId: s(40),  orderNumber: 3 },
    { routeId: 12, spotId: s(41),  orderNumber: 4 },
    { routeId: 12, spotId: s(36),  orderNumber: 5 },
    // route 13
    { routeId: 13, spotId: s(45),  orderNumber: 1 },
    { routeId: 13, spotId: s(47),  orderNumber: 2 },
    { routeId: 13, spotId: s(43),  orderNumber: 3 },
    { routeId: 13, spotId: s(46),  orderNumber: 4 },
    // route 14
    { routeId: 14, spotId: s(44),  orderNumber: 1 },
    { routeId: 14, spotId: s(48),  orderNumber: 2 },
    { routeId: 14, spotId: s(49),  orderNumber: 3 },
    { routeId: 14, spotId: s(43),  orderNumber: 4 },
    // route 15
    { routeId: 15, spotId: s(51),  orderNumber: 1 },
    { routeId: 15, spotId: s(54),  orderNumber: 2 },
    { routeId: 15, spotId: s(52),  orderNumber: 3 },
    { routeId: 15, spotId: s(50),  orderNumber: 4 },
    // route 16
    { routeId: 16, spotId: s(53),  orderNumber: 1 },
    { routeId: 16, spotId: s(56),  orderNumber: 2 },
    { routeId: 16, spotId: s(55),  orderNumber: 3 },
    { routeId: 16, spotId: s(50),  orderNumber: 4 },
    // route 17
    { routeId: 17, spotId: s(61),  orderNumber: 1 },
    { routeId: 17, spotId: s(62),  orderNumber: 2 },
    { routeId: 17, spotId: s(60),  orderNumber: 3 },
    { routeId: 17, spotId: s(57),  orderNumber: 4 },
    // route 18
    { routeId: 18, spotId: s(59),  orderNumber: 1 },
    { routeId: 18, spotId: s(58),  orderNumber: 2 },
    { routeId: 18, spotId: s(57),  orderNumber: 3 },
    { routeId: 18, spotId: s(63),  orderNumber: 4 },
    // route 19
    { routeId: 19, spotId: s(67),  orderNumber: 1 },
    { routeId: 19, spotId: s(64),  orderNumber: 2 },
    { routeId: 19, spotId: s(65),  orderNumber: 3 },
    { routeId: 19, spotId: s(70),  orderNumber: 4 },
    // route 20
    { routeId: 20, spotId: s(68),  orderNumber: 1 },
    { routeId: 20, spotId: s(64),  orderNumber: 2 },
    { routeId: 20, spotId: s(66),  orderNumber: 3 },
    { routeId: 20, spotId: s(69),  orderNumber: 4 },
    // route 21
    { routeId: 21, spotId: s(74),  orderNumber: 1 },
    { routeId: 21, spotId: s(73),  orderNumber: 2 },
    { routeId: 21, spotId: s(72),  orderNumber: 3 },
    { routeId: 21, spotId: s(71),  orderNumber: 4 },
    // route 22
    { routeId: 22, spotId: s(76),  orderNumber: 1 },
    { routeId: 22, spotId: s(77),  orderNumber: 2 },
    { routeId: 22, spotId: s(75),  orderNumber: 3 },
    { routeId: 22, spotId: s(71),  orderNumber: 4 },
    // route 23
    { routeId: 23, spotId: s(79),  orderNumber: 1 },
    { routeId: 23, spotId: s(78),  orderNumber: 2 },
    { routeId: 23, spotId: s(84),  orderNumber: 3 },
    { routeId: 23, spotId: s(81),  orderNumber: 4 },
    // route 24
    { routeId: 24, spotId: s(78),  orderNumber: 1 },
    { routeId: 24, spotId: s(80),  orderNumber: 2 },
    { routeId: 24, spotId: s(83),  orderNumber: 3 },
    { routeId: 24, spotId: s(82),  orderNumber: 4 },
    // route 25
    { routeId: 25, spotId: s(88),  orderNumber: 1 },
    { routeId: 25, spotId: s(86),  orderNumber: 2 },
    { routeId: 25, spotId: s(91),  orderNumber: 3 },
    { routeId: 25, spotId: s(85),  orderNumber: 4 },
    // route 26
    { routeId: 26, spotId: s(87),  orderNumber: 1 },
    { routeId: 26, spotId: s(90),  orderNumber: 2 },
    { routeId: 26, spotId: s(89),  orderNumber: 3 },
    { routeId: 26, spotId: s(85),  orderNumber: 4 },
    // route 27
    { routeId: 27, spotId: s(184), orderNumber: 1 },
    { routeId: 27, spotId: s(175), orderNumber: 2 },
    { routeId: 27, spotId: s(125), orderNumber: 3 },
    { routeId: 27, spotId: s(115), orderNumber: 4 },
    { routeId: 27, spotId: s(10),  orderNumber: 5 },
    { routeId: 27, spotId: s(103), orderNumber: 6 },
    // route 28
    { routeId: 28, spotId: s(148), orderNumber: 1 },
    { routeId: 28, spotId: s(151), orderNumber: 2 },
    { routeId: 28, spotId: s(163), orderNumber: 3 },
    { routeId: 28, spotId: s(186), orderNumber: 4 },
    { routeId: 28, spotId: s(10),  orderNumber: 5 },
    // route 29
    { routeId: 29, spotId: s(158), orderNumber: 1 },
    { routeId: 29, spotId: s(170), orderNumber: 2 },
    { routeId: 29, spotId: s(178), orderNumber: 3 },
    { routeId: 29, spotId: s(166), orderNumber: 4 },
    { routeId: 29, spotId: s(92),  orderNumber: 5 },
    // route 30
    { routeId: 30, spotId: s(144), orderNumber: 1 },
    { routeId: 30, spotId: s(123), orderNumber: 2 },
    { routeId: 30, spotId: s(196), orderNumber: 3 },
    { routeId: 30, spotId: s(174), orderNumber: 4 },
    { routeId: 30, spotId: s(92),  orderNumber: 5 },
    // route 31
    { routeId: 31, spotId: s(204), orderNumber: 1 },
    { routeId: 31, spotId: s(122), orderNumber: 2 },
    { routeId: 31, spotId: s(188), orderNumber: 3 },
    { routeId: 31, spotId: s(93),  orderNumber: 4 },
    // route 32
    { routeId: 32, spotId: s(205), orderNumber: 1 },
    { routeId: 32, spotId: s(122), orderNumber: 2 },
    { routeId: 32, spotId: s(203), orderNumber: 3 },
    { routeId: 32, spotId: s(93),  orderNumber: 4 },
    // route 33
    { routeId: 33, spotId: s(107), orderNumber: 1 },
    { routeId: 33, spotId: s(105), orderNumber: 2 },
    { routeId: 33, spotId: s(135), orderNumber: 3 },
    { routeId: 33, spotId: s(136), orderNumber: 4 },
    // route 34
    { routeId: 34, spotId: s(106), orderNumber: 1 },
    { routeId: 34, spotId: s(164), orderNumber: 2 },
    { routeId: 34, spotId: s(202), orderNumber: 3 },
    { routeId: 34, spotId: s(117), orderNumber: 4 },
    { routeId: 34, spotId: s(107), orderNumber: 5 },
    // route 35
    { routeId: 35, spotId: s(189), orderNumber: 1 },
    { routeId: 35, spotId: s(119), orderNumber: 2 },
    { routeId: 35, spotId: s(172), orderNumber: 3 },
    { routeId: 35, spotId: s(147), orderNumber: 4 },
    { routeId: 35, spotId: s(59),  orderNumber: 5 },
    // route 36 (동대문 성곽공원 spotId 없으므로 스킵)
    { routeId: 36, spotId: s(127), orderNumber: 1 },
    { routeId: 36, spotId: s(198), orderNumber: 2 },
    { routeId: 36, spotId: s(157), orderNumber: 4 },
    { routeId: 36, spotId: s(59),  orderNumber: 5 },
    // route 37
    { routeId: 37, spotId: s(169), orderNumber: 1 },
    { routeId: 37, spotId: s(168), orderNumber: 2 },
    { routeId: 37, spotId: s(142), orderNumber: 3 },
    { routeId: 37, spotId: s(139), orderNumber: 4 },
    { routeId: 37, spotId: s(95),  orderNumber: 5 },
    // route 38
    { routeId: 38, spotId: s(143), orderNumber: 1 },
    { routeId: 38, spotId: s(142), orderNumber: 2 },
    { routeId: 38, spotId: s(140), orderNumber: 3 },
    { routeId: 38, spotId: s(95),  orderNumber: 4 },
    { routeId: 38, spotId: s(141), orderNumber: 5 },
    // route 39
    { routeId: 39, spotId: s(118), orderNumber: 1 },
    { routeId: 39, spotId: s(171), orderNumber: 2 },
    { routeId: 39, spotId: s(124), orderNumber: 3 },
    { routeId: 39, spotId: s(182), orderNumber: 4 },
    { routeId: 39, spotId: s(96),  orderNumber: 5 },
    // route 40
    { routeId: 40, spotId: s(199), orderNumber: 1 },
    { routeId: 40, spotId: s(200), orderNumber: 2 },
    { routeId: 40, spotId: s(201), orderNumber: 3 },
    { routeId: 40, spotId: s(198), orderNumber: 4 },
    { routeId: 40, spotId: s(96),  orderNumber: 5 },
    // route 41
    { routeId: 41, spotId: s(185), orderNumber: 1 },
    { routeId: 41, spotId: s(128), orderNumber: 2 },
    { routeId: 41, spotId: s(171), orderNumber: 3 },
    { routeId: 41, spotId: s(97),  orderNumber: 4 },
    { routeId: 41, spotId: s(118), orderNumber: 4 },
    { routeId: 41, spotId: s(198), orderNumber: 5 },
    // route 42
    { routeId: 42, spotId: s(138), orderNumber: 1 },
    { routeId: 42, spotId: s(145), orderNumber: 2 },
    { routeId: 42, spotId: s(116), orderNumber: 3 },
    { routeId: 42, spotId: s(97),  orderNumber: 4 },
    { routeId: 42, spotId: s(131), orderNumber: 5 },
    { routeId: 42, spotId: s(173), orderNumber: 6 },
    // route 43
    { routeId: 43, spotId: s(193), orderNumber: 1 },
    { routeId: 43, spotId: s(160), orderNumber: 2 },
    { routeId: 43, spotId: s(195), orderNumber: 3 },
    { routeId: 43, spotId: s(98),  orderNumber: 4 },
    { routeId: 43, spotId: s(132), orderNumber: 5 },
    { routeId: 43, spotId: s(194), orderNumber: 6 },
    // route 44
    { routeId: 44, spotId: s(114), orderNumber: 1 },
    { routeId: 44, spotId: s(159), orderNumber: 2 },
    { routeId: 44, spotId: s(129), orderNumber: 3 },
    { routeId: 44, spotId: s(191), orderNumber: 4 },
    { routeId: 44, spotId: s(98),  orderNumber: 5 },
    // route 45
    { routeId: 45, spotId: s(161), orderNumber: 1 },
    { routeId: 45, spotId: s(130), orderNumber: 2 },
    { routeId: 45, spotId: s(153), orderNumber: 3 },
    { routeId: 45, spotId: s(99),  orderNumber: 4 },
    { routeId: 45, spotId: s(165), orderNumber: 5 },
    // route 46
    { routeId: 46, spotId: s(150), orderNumber: 1 },
    { routeId: 46, spotId: s(156), orderNumber: 2 },
    { routeId: 46, spotId: s(137), orderNumber: 3 },
    { routeId: 46, spotId: s(155), orderNumber: 4 },
    { routeId: 46, spotId: s(99),  orderNumber: 5 },
    // route 47
    { routeId: 47, spotId: s(146), orderNumber: 1 },
    { routeId: 47, spotId: s(126), orderNumber: 2 },
    { routeId: 47, spotId: s(152), orderNumber: 3 },
    { routeId: 47, spotId: s(59),  orderNumber: 4 },
    { routeId: 47, spotId: s(100), orderNumber: 5 },
    { routeId: 47, spotId: s(183), orderNumber: 6 },
    // route 48
    { routeId: 48, spotId: s(118), orderNumber: 1 },
    { routeId: 48, spotId: s(171), orderNumber: 2 },
    { routeId: 48, spotId: s(124), orderNumber: 3 },
    { routeId: 48, spotId: s(192), orderNumber: 4 },
    { routeId: 48, spotId: s(100), orderNumber: 5 },
    { routeId: 48, spotId: s(59),  orderNumber: 6 },
    // route 49
    { routeId: 49, spotId: s(104), orderNumber: 1 },
    { routeId: 49, spotId: s(111), orderNumber: 2 },
    { routeId: 49, spotId: s(162), orderNumber: 3 },
    { routeId: 49, spotId: s(101), orderNumber: 4 },
    { routeId: 49, spotId: s(113), orderNumber: 5 },
    // route 50
    { routeId: 50, spotId: s(109), orderNumber: 1 },
    { routeId: 50, spotId: s(113), orderNumber: 2 },
    { routeId: 50, spotId: s(108), orderNumber: 3 },
    { routeId: 50, spotId: s(101), orderNumber: 4 },
    { routeId: 50, spotId: s(110), orderNumber: 5 },
    // route 51
    { routeId: 51, spotId: s(149), orderNumber: 1 },
    { routeId: 51, spotId: s(148), orderNumber: 2 },
    { routeId: 51, spotId: s(177), orderNumber: 3 },
    { routeId: 51, spotId: s(102), orderNumber: 4 },
    { routeId: 51, spotId: s(151), orderNumber: 5 },
    // route 52
    { routeId: 52, spotId: s(146), orderNumber: 1 },
    { routeId: 52, spotId: s(126), orderNumber: 2 },
    { routeId: 52, spotId: s(112), orderNumber: 3 },
    { routeId: 52, spotId: s(152), orderNumber: 4 },
    { routeId: 52, spotId: s(102), orderNumber: 5 },
    { routeId: 52, spotId: s(133), orderNumber: 6 },
    // route 53
    { routeId: 53, spotId: s(154), orderNumber: 1 },
    { routeId: 53, spotId: s(167), orderNumber: 2 },
    { routeId: 53, spotId: s(187), orderNumber: 3 },
    { routeId: 53, spotId: s(103), orderNumber: 4 },
    { routeId: 53, spotId: s(10),  orderNumber: 5 },
    { routeId: 53, spotId: s(190), orderNumber: 6 },
    // route 54
    { routeId: 54, spotId: s(197), orderNumber: 1 },
    { routeId: 54, spotId: s(134), orderNumber: 2 },
    { routeId: 54, spotId: s(121), orderNumber: 3 },
    { routeId: 54, spotId: s(120), orderNumber: 4 },
    { routeId: 54, spotId: s(103), orderNumber: 5 },
  ];

  await prisma.routeSpot.createMany({
    data: routeSpots,
    skipDuplicates: true,
  });

  console.log('✅ 왕 27명 + 태그 + 장소 204개 + 왕 위치 27개 + 루트 54개 + 루트 장소 삽입 완료!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
